#--STAGE-1-----------

FROM node:17-alpine AS build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

#--STAGE-2-----------

FROM nginx

COPY --from=build /app/build /usr/share/nginx/html